language: node_js
node_js:
  - 10.16.0
before_script:
  - rm -rf ./test
  - npm run build
script:
  - npm run initialize:test
env:
  - NODE_ENV=development API_URL=https://headless-spa-mock-api.herokuapp.com BASE_URL=https://your-subpage-link.dk
notifications:
  slack:
    secure: QXpHmFfW0TXXjY1K5kWCNVqZPQwilXjORBqOiyA+2teW9L9HguR8jq88fx0vqqMhMxVs4+o8hif22CoamihuMPb6zcrqMRWzi6LdLgXSJcjAeTorwVymNgPKz3+gmeB7fwGl+8A6F64bljW5Y2Q+csTVh0qG79z+Ecw99jRujLGHiK/6s3wJ8k11oJXGGcp2cgDfM09aIqwfPtgwFS6ErLLOH44MsDRU+KEopTdjI5kRWCZW8PF8GjYDldpBeY738/6WPC7nhbtT2Zc5oS7FtsrplDZY/xiprZJQuT59lyZo+93iFYEW/IdT42UzR0O5pJLsVeGuMzWKf4cokSmD3bKXUb2NoOOTyStJPKAQ1qy7LdbhZw0D8PEIM+U3g0eJ084YEMObwe34zusiFvz6KrxkEP7Z1n0sDZFSHq15nV9Yt551Q4QJynrgaZJAqg0omytCKvNkh/OODKk3a/1ulC4umIDgy74u/7ua4ckaSqjKRtOHgG2DBFSQb5U0od2FvvPiKh7rLBI5x4R/fd6FjqJH5BWUqKgwLGILC0j+mW5JPRbb1yAsyGTqhUwkVfB09lrduAvqIoc6WLSgl5pRipIwO1nKjlsc2nMi+U+ngYBliuYaX70GJ6M9Ic4XbbL6tZSAql3J27TyMYu+HTrQQzQ7R5+7wZR4W2Vbuz6mSwQ=
